name: 更新 MosDNS 的 GeoIP 和 GeoSite 规则

# 触发条件：每天定时运行或手动触发
on:
  schedule:
    - cron: '0 6 * * *' # 每天北京时间 14:00（UTC 6:00）
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # sing-box 需要 Go 1.22 或更高版本

      # 3. 安装 sing-box 的 sing-geoip 和 sing-geosite 工具
      - name: 安装 sing-box 工具
        run: |
          go install github.com/sagernet/sing-box/cmd/sing-geoip@latest
          go install github.com/sagernet/sing-box/cmd/sing-geosite@latest
          mv ~/go/bin/sing-geoip .
          mv ~/go/bin/sing-geosite .
          chmod +x sing-geoip sing-geosite

      # 4. 下载最新的 geoip.dat 和 geosite.dat
      - name: 下载 geoip.dat 和 geosite.dat
        run: |
          wget -O geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget -O geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

      # 5. 解压 geoip.dat 和 geosite.dat 为 MosDNS 规则文件
      - name: 转换 geoip.dat 和 geosite.dat
        run: |
          mkdir -p rule
          ./sing-geoip -o rule/geoip_cn.txt cn geoip.dat # 提取 geoip:cn
          ./sing-geosite -o rule/geosite_cn.txt cn geosite.dat # 提取 geosite:cn
          ./sing-geosite -o rule/geosite_geolocation-!cn.txt geolocation-!cn geosite.dat # 提取 geosite:geolocation-!cn
          ./sing-geosite -o rule/geosite_category-ads-all.txt category-ads-all geosite.dat # 提取广告域名

      # 6. 检查生成的文件
      - name: 列出生成的文件
        run: ls -l rule/

      # 7. 验证生成的文件
      - name: 验证生成的文件
        run: |
          for file in rule/*.txt; do
            if [ ! -s "$file" ]; then
              echo "错误：$file 为空"
              exit 1
            fi
          done

      # 8. 提交并推送更改
      - name: 提交并推送更改
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add rule/*
          git diff-index --quiet HEAD || git commit -m "更新 MosDNS 规则文件（geoip.dat 和 geosite.dat）"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
