name: 更新 MosDNS 的 GeoIP 和 GeoSite 规则

on:
  schedule:
    - cron: '0 6 * * *' # 每天北京时间 14:00（UTC 6:00）
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 3. 克隆 v2ray-core 并构建特定版本的 v2dat
      - name: 构建 v2dat
        run: |
          git clone https://github.com/v2fly/v2ray-core.git
          cd v2ray-core
          git checkout v4.45.2 # 使用支持 unpack 的版本
          go build -o v2dat ./main
          mv v2dat ../
          cd ..
          chmod +x v2dat

      # 4. 下载最新的 geoip.dat 和 geosite.dat
      - name: 下载 geoip.dat 和 geosite.dat
        run: |
          wget -O geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget -O geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

      # 5. 解压 geoip.dat 和 geosite.dat 为 MosDNS 规则文件
      - name: 转换 geoip.dat 和 geosite.dat
        run: |
          mkdir -p rule
          ./v2dat unpack geoip -o rule -f cn geoip.dat # 提取 geoip:cn
          ./v2dat unpack geosite -o rule -f cn geosite.dat # 提取 geosite:cn
          ./v2dat unpack geosite -o rule -f 'geolocation-!cn' geosite.dat # 提取 geosite:geolocation-!cn
          ./v2dat unpack geosite -o rule -f 'category-ads-all' geosite.dat # 提取广告域名

      # 6. 检查生成的文件
      - name: 列出生成的文件
        run: ls -l rule/

      # 7. 验证生成的文件
      - name: 验证生成的文件
        run: |
          for file in rule/*.txt; do
            if [ ! -s "$file" ]; then
              echo "错误：$file 为空"
              exit 1
            fi
          done

      # 8. 提交并推送更改
      - name: 提交并推送更改
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add rule/*
          git diff-index --quiet HEAD || git commit -m "更新 MosDNS 规则文件（geoip.dat 和 geosite.dat）"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
