name: Update GeoIP and GeoSite

on:
  schedule:
    - cron: '10 0 * * *' # 每天 UTC 00:10 运行（北京时间 08:10）
  workflow_dispatch: # 支持手动触发

jobs:
  update-geo:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 安装 v2ray-geosite
      - name: Install v2ray-geosite
        run: pip install v2ray-geosite

      # 下载最新的 geosite.dat 和 geoip.dat
      - name: Download Geo Files
        run: |
          mkdir -p rules
          wget https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat -O rules/geosite.dat
          wget https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat -O rules/geoip.dat

      # 运行导出脚本
      - name: Export Rules
        run: bash scripts/update-geo.sh

      # 提交更改到仓库
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add rules/
          git commit -m "Update GeoIP and GeoSite rules: $(date -u)" || exit 0
          git push
